-- Evidence must describe the provider that will serve the NEXT order.
--
-- Ownership is per SERVICE (a service HeroSMS carries goes entirely to HeroSMS;
-- one it does not stays entirely on SMSPVA), but `services.observed_*` and
-- `countries.observed_*` are single columns with no provider dimension. Running
-- the provider-scoped refreshes once per provider therefore made the two passes
-- CLOBBER each other: each wipes the rows the other just wrote, and whichever
-- ran last won.
--
-- Worse, the surviving numbers described a retired provider. Measured
-- 2026-07-30: facebook is served by HeroSMS, yet its service evidence read
-- 14 attempts / 6 codes — all SMSPVA, plus 32 smspool and 3 virtualsms orders
-- sitting in the same 30-day window from providers we no longer use at all.
--
-- Fix, in both functions: only ever count an order whose provider still OWNS
-- that service, and only ever wipe rows belonging to the provider being
-- refreshed. Retired providers drop out by construction.
--
-- Both bodies below are the LIVE definitions with exactly those predicates
-- added — generated by patching `pg_get_functiondef` output rather than being
-- retyped, because re-creating a function from a dump is how `run_watchdog`
-- silently lost a branch and a threshold.

CREATE OR REPLACE FUNCTION public.refresh_service_delivery(p_lookback interval DEFAULT '30 days'::interval, p_provider text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_updated integer;
  v_provider text := coalesce(p_provider, public.active_sms_provider());
begin
  update public.services s
  set observed_attempts = null, observed_codes = null, observed_orders = null
  where (s.observed_attempts is not null or s.observed_orders is not null)
    and exists (select 1 from public.routes r
                where r.service_id = s.id and r.provider = v_provider
                  and r.status = 'active')
    and not exists (
      select 1 from public.orders o
      where o.service_id = s.id
        and o.provider = v_provider
        and o.tier = 'standard'
        and o.created_at >= now() - p_lookback
        and o.closed_at is not null
        and o.smspva_number is not null
        and o.user_id <> '825688de-6117-4251-9f90-93b83b41b572'
    );

  with classified as (
    select o.service_id,
      (o.otp is not null) as is_code,
      (
        o.otp is not null
        or o.status = 'received'
        or o.status = 'expired'
        or (o.status = 'canceled' and o.closed_at - o.created_at >= interval '240 seconds')
        or (o.status = 'canceled' and exists (
              select 1 from public.orders n
              where n.user_id = o.user_id
                and n.service_id = o.service_id
                and n.id <> o.id
                and n.created_at >= o.closed_at
                and n.created_at < o.closed_at + interval '10 minutes'))
      ) as is_conclusive
    from public.orders o
    where o.created_at >= now() - p_lookback
      and o.closed_at is not null
      and o.provider = v_provider
      and exists (select 1 from public.routes r
                  where r.service_id = o.service_id and r.provider = v_provider
                    and r.status = 'active')
      and o.tier = 'standard'
      and o.user_id <> '825688de-6117-4251-9f90-93b83b41b572'
      and o.smspva_number is not null
  ),
  agg as (
    select service_id,
           count(*) filter (where is_conclusive) as attempts,
           count(*) filter (where is_code)       as codes,
           count(*)                              as orders
    from classified group by service_id
  ),
  upd as (
    update public.services s
    set observed_attempts = agg.attempts,
        observed_codes    = agg.codes,
        observed_orders   = agg.orders
    from agg where s.id = agg.service_id
    returning 1
  )
  select count(*) into v_updated from upd;
  return v_updated;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_country_delivery(p_lookback interval DEFAULT '30 days'::interval, p_provider text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_updated integer;
  -- p_provider is accepted for signature compatibility and deliberately UNUSED.
  -- A country is not owned by a provider, so scoping it to one wiped the
  -- other's evidence on the next pass.
begin
  -- Conditional wipe: only clear a country the new window genuinely has
  -- nothing to say about. An unconditional reset leaves quiet countries NULL
  -- and permanently unrankable.
  update public.countries c
  set observed_attempts = null, observed_codes = null, observed_orders = null
  where (c.observed_attempts is not null or c.observed_orders is not null)
    and not exists (
      select 1 from public.orders o
      where o.country_id = c.id
        and exists (select 1 from public.routes r
                  where r.service_id = o.service_id and r.provider = o.provider
                    and r.status = 'active')
        and o.tier = 'standard'
        and o.created_at >= now() - p_lookback
        and o.closed_at is not null
        and o.smspva_number is not null
        and o.user_id <> '825688de-6117-4251-9f90-93b83b41b572'
    );

  with classified as (
    select o.country_id,
      -- A rescued code sits on a `canceled` row, so status is not the signal.
      (o.otp is not null) as is_code,
      (
        o.otp is not null
        or o.status = 'received'
        or o.status = 'expired'
        or (o.status = 'canceled' and o.closed_at - o.created_at >= interval '240 seconds')
        or (o.status = 'canceled' and exists (
              select 1 from public.orders n
              where n.user_id = o.user_id
                and n.country_id = o.country_id
                and n.id <> o.id
                and n.created_at >= o.closed_at
                and n.created_at < o.closed_at + interval '10 minutes'))
      ) as is_conclusive
    from public.orders o
    where o.created_at >= now() - p_lookback
      and o.closed_at is not null
      and exists (select 1 from public.routes r
                  where r.service_id = o.service_id and r.provider = o.provider
                    and r.status = 'active')
      and o.tier = 'standard'
      and o.user_id <> '825688de-6117-4251-9f90-93b83b41b572'
      -- Orders that never held a number are not delivery evidence.
      and o.smspva_number is not null
  ),
  agg as (
    select country_id,
           count(*) filter (where is_conclusive) as attempts,
           count(*) filter (where is_code)       as codes,
           count(*)                              as orders
    from classified group by country_id
  ),
  upd as (
    update public.countries c
    set observed_attempts = agg.attempts,
        observed_codes    = agg.codes,
        observed_orders   = agg.orders
    from agg where agg.country_id = c.id
    returning 1
  )
  select count(*) into v_updated from upd;

  return v_updated;
end;
$function$
;

revoke execute on function public.refresh_service_delivery(interval, text)
  from public, anon, authenticated;
revoke execute on function public.refresh_country_delivery(interval, text)
  from public, anon, authenticated;

-- Wrapper: routes and services are per-provider; countries are not.
create or replace function public.refresh_evidence_all_providers(
  p_lookback   interval default '30 days'::interval,
  p_min_sample integer  default 3
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_provider  text;
  v_out       jsonb := '{}'::jsonb;
  v_routes    integer;
  v_services  integer;
  v_countries integer;
begin
  for v_provider in
    select distinct provider
    from public.routes
    where status = 'active' and provider is not null
    order by 1
  loop
    -- `routes` carries a provider column, so these are naturally disjoint.
    -- `services` is made disjoint by the ownership predicate added above.
    v_routes   := public.refresh_route_observed_success(p_lookback, p_min_sample, v_provider);
    v_services := public.refresh_service_delivery(p_lookback, v_provider);

    v_out := v_out || jsonb_build_object(v_provider, jsonb_build_object(
      'routes', v_routes, 'services', v_services));
  end loop;

  -- ONCE, outside the loop: country evidence spans providers, and now filters
  -- to current-owner orders on its own.
  v_countries := public.refresh_country_delivery(p_lookback);

  return v_out || jsonb_build_object('countries', v_countries);
end;
$$;

revoke execute on function public.refresh_evidence_all_providers(interval, integer)
  from public, anon, authenticated;
