-- Default privileges: stop every FUTURE table being world-writable and every
-- FUTURE function being world-callable.
--
-- anon and authenticated held `arwdDxtm` (INSERT/SELECT/UPDATE/DELETE/TRUNCATE/
-- REFERENCES/TRIGGER/MAINTAIN) on every future table in public, and EXECUTE on
-- every future function. So the next migration that adds a table and forgets
-- `enable row level security` ships a world-readable AND world-WRITABLE table at
-- /rest/v1/<table>, and the next SECURITY DEFINER function that forgets its
-- revoke is callable at /rest/v1/rpc/<name>.
--
-- That is exactly how run_watchdog became publicly callable. The codebase
-- compensates with 64 hand-written `revoke execute` lines across 35 migrations
-- — discipline as the only control, one omission from a breach.
--
-- SELECT is deliberately retained: the catalog tables (services, countries,
-- routes, esim_plans) depend on it, and RLS still governs row visibility.
--
-- APPLIED 2026-07-27. Verified after: postgres tables arwdDxtm -> rxtm,
-- postgres functions X -> (none). The two functions clients legitimately call
-- (claim_daily_credit, daily_credit_status) hold EXPLICIT grants and are
-- unaffected — confirmed still callable by `authenticated`; run_watchdog and
-- begin_order confirmed still not callable.
alter default privileges in schema public
  revoke insert, update, delete, truncate on tables from anon, authenticated;
alter default privileges in schema public
  revoke execute on functions from anon, authenticated;

-- ── NOT APPLIED: the supabase_admin half. ────────────────────────────────────
--
-- `ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin` requires membership in
-- that role. The CLI connects as `postgres`, which is a member of postgres but
-- NOT of supabase_admin (verified: pg_has_role(...,'supabase_admin','MEMBER')
-- is false), so those statements fail with "42501: permission denied to change
-- default privileges".
--
-- Impact of leaving them: objects created BY supabase_admin — i.e. through the
-- Supabase dashboard / SQL editor rather than a migration — still inherit the
-- old permissive defaults. Everything created by migrations (which run as
-- postgres) is now covered, so this is the smaller half of the risk, but it is
-- not zero.
--
-- To finish, run these from the Supabase SQL editor:
--
--   alter default privileges for role supabase_admin in schema public
--     revoke insert, update, delete, truncate on tables from anon, authenticated;
--   alter default privileges for role supabase_admin in schema public
--     revoke execute on functions from anon, authenticated;
--
-- Verify with:
--   select pg_get_userbyid(defaclrole) as grantor, defaclobjtype, defaclacl
--     from pg_default_acl d join pg_namespace n on n.oid = d.defaclnamespace
--    where n.nspname = 'public';
